from __future__ import annotations

from pathlib import Path
from typing import Any

from code_agent.assets.mesh.request_adapter import positive_vector3, request_size, vector3
from code_agent.assets.mesh.workflow.summary import load_mesh_asset_summary


def manifest_entry_from_bundle(request: dict[str, Any], bundle: Any) -> dict[str, Any]:
    repair = bundle.repair
    manifold = bundle.manifold
    runtime_path = repair.output_mesh_path if repair is not None and repair.ok else bundle.generation.mesh_path
    summary = load_mesh_asset_summary(runtime_path)
    desired_size = request_size(request)
    mesh_bbox = vector3(summary.get("bbox_size"))
    file_meshes_are_zup = False
    genesis_bbox = _bbox_after_yup_to_zup(mesh_bbox)
    scale = _scale_to_bbox(genesis_bbox, desired_size) or [1.0, 1.0, 1.0]
    visual_path = visual_mesh_path(bundle) or runtime_path
    texture_path = texture_path_from_bundle(bundle)
    notes = [
        "Generated by the Planner-callable mesh asset action.",
        "Use runtime_path as the strict-manifold Genesis geometry for simulation/collision.",
        "visual_path is the seam-aware textured render artifact for the same logical asset, not a separate object to "
        "instantiate as an independent simulation body.",
        "Pass file_meshes_are_zup and scale exactly as listed; generated OBJ assets are provider Y-up unless stated "
        "otherwise.",
        "If texture transfer succeeded, visual_path binds the rebaked base color through its neighboring MTL file while "
        "runtime_path remains the repaired manifold geometry.",
        "Use texture_path as evidence metadata for the transferred base-color image and for texture preview checks.",
    ]
    if repair is None or not repair.ok:
        notes.append(
            "Mesh repair did not produce a ready repaired mesh; runtime_path falls back to the downloaded mesh."
        )
    if desired_size is not None and genesis_bbox is not None:
        notes.append("Scale was estimated from requested size and mesh bbox after Y-up to Genesis Z-up conversion.")
    status = "ready" if repair is not None and repair.ok and manifold is not None and manifold.ok else "failed"
    return {
        "logical_name": str(request.get("name", "mesh_asset")),
        "source_type": "generated_mesh",
        "runtime_path": str(runtime_path.resolve()),
        "visual_path": str(visual_path.resolve()) if visual_path is not None else None,
        "scale": scale,
        "bbox": desired_size or genesis_bbox,
        "file_meshes_are_zup": file_meshes_are_zup,
        "texture_path": str(texture_path.resolve()) if texture_path is not None else None,
        "simulation_role": str(request.get("simulation_role", "scene prop")),
        "status": status,
        "notes": notes,
    }


def visual_mesh_path(bundle: Any) -> Path | None:
    transfer = bundle.texture_transfer
    if transfer is not None and transfer.ok and transfer.output_mesh_path is not None:
        return transfer.output_mesh_path
    texture = bundle.texture
    if texture is not None and texture.ok and texture.textured_mesh_path is not None:
        return texture.textured_mesh_path
    return None


def texture_path_from_bundle(bundle: Any) -> Path | None:
    transfer = bundle.texture_transfer
    if transfer is not None and transfer.ok and transfer.output_texture_path is not None:
        return transfer.output_texture_path
    texture = bundle.texture
    if texture is not None and texture.ok:
        return texture.texture_paths.get("base_color")
    return None


def failed_manifest_entry(request: dict[str, Any], error: str) -> dict[str, Any]:
    return {
        "logical_name": str(request.get("name", "mesh_asset")),
        "source_type": "generated_mesh",
        "runtime_path": "unavailable",
        "visual_path": None,
        "scale": positive_vector3(request.get("scale")),
        "bbox": request_size(request),
        "file_meshes_are_zup": False,
        "texture_path": None,
        "simulation_role": str(request.get("simulation_role", "scene prop")),
        "status": "failed",
        "notes": [error],
    }


def build_manifest(entries: list[dict[str, Any]], *, skipped_names: list[str]) -> dict[str, Any]:
    unresolved = [entry["logical_name"] for entry in entries if entry.get("status") != "ready"]
    unresolved.extend(f"Skipped asset request: {name}" for name in skipped_names)
    return {
        "assets": entries,
        "assumptions": [
            "Generated mesh runtime paths are written before code writers run, so workers should read this manifest.",
        ],
        "unresolved_risks": unresolved,
    }


def _scale_to_bbox(mesh_bbox: list[float] | None, request_bbox: list[float] | None) -> list[float] | None:
    if mesh_bbox is None or request_bbox is None:
        return None
    scale: list[float] = []
    for mesh_size, requested_size in zip(mesh_bbox, request_bbox, strict=True):
        if mesh_size <= 0 or requested_size <= 0:
            return None
        scale.append(float(requested_size) / float(mesh_size))
    return scale


def _bbox_after_yup_to_zup(mesh_bbox: list[float] | None) -> list[float] | None:
    if mesh_bbox is None:
        return None
    return [float(mesh_bbox[0]), float(mesh_bbox[2]), float(mesh_bbox[1])]
