from __future__ import annotations

from pathlib import Path
from typing import Any

from code_agent.assets.mesh.request_adapter import request_size, vector3
from code_agent.assets.mesh.workflow.summary import load_mesh_asset_summary


def manifest_entry_from_bundle(request: dict[str, Any], bundle: Any) -> dict[str, Any]:
    repair = bundle.repair
    manifold = bundle.manifold
    runtime_path = repair.output_mesh_path if repair is not None and repair.ok else bundle.generation.mesh_path
    file_meshes_are_zup = False
    scale_metadata = _scale_metadata_from_request(request, runtime_path)
    visual_path = visual_mesh_path(bundle) or runtime_path
    texture_path = texture_path_from_bundle(bundle)
    genesis_fem_import = getattr(bundle, "genesis_fem_import", None)
    ready = (
        repair is not None
        and repair.ok
        and manifold is not None
        and manifold.ok
        and genesis_fem_import is not None
        and genesis_fem_import.ok
    )
    return {
        "logical_name": str(request.get("name", "mesh_asset")),
        "source_type": "generated_mesh",
        "runtime_path": str(runtime_path.resolve()),
        "visual_path": str(visual_path.resolve()) if visual_path is not None else None,
        "scale": scale_metadata["scale"],
        "bbox": scale_metadata["runtime_bbox"] or scale_metadata["genesis_bbox"],
        "file_meshes_are_zup": file_meshes_are_zup,
        "texture_path": str(texture_path.resolve()) if texture_path is not None else None,
        "validation": {
            "manifold": None if manifold is None else manifold.to_dict(),
            "genesis_fem_import": None if genesis_fem_import is None else genesis_fem_import.to_dict(),
        },
        "asset_request": _manifest_asset_request(request),
        "simulation_role": str(request.get("simulation_role", "scene prop")),
        "status": "ready" if ready else "failed",
        "notes": _generated_mesh_notes(
            repair=repair,
            genesis_fem_import=genesis_fem_import,
            scale_metadata=scale_metadata,
        ),
    }


def manifest_entry_from_ready_entry_with_request(
    request: dict[str, Any],
    entry: dict[str, Any],
    *,
    genesis_fem_import: Any | None = None,
) -> dict[str, Any]:
    runtime_path = Path(str(entry.get("runtime_path", "")))
    file_meshes_are_zup = entry.get("file_meshes_are_zup")
    if not isinstance(file_meshes_are_zup, bool):
        file_meshes_are_zup = False
    scale_metadata = _scale_metadata_from_request(request, runtime_path)
    updated = dict(entry)
    validation = dict(updated.get("validation") or {})
    if genesis_fem_import is not None:
        validation["genesis_fem_import"] = genesis_fem_import.to_dict()
    notes = list(updated.get("notes") or [])
    notes.append(
        "Mesh geometry was reused; runtime scale/bbox metadata was refreshed without a new Meshy generation request."
    )
    updated.update(
        {
            "scale": scale_metadata["scale"],
            "bbox": scale_metadata["runtime_bbox"] or scale_metadata["genesis_bbox"],
            "file_meshes_are_zup": file_meshes_are_zup,
            "validation": validation,
            "asset_request": _manifest_asset_request(request),
            "simulation_role": str(request.get("simulation_role", updated.get("simulation_role", "scene prop"))),
            "status": "ready" if genesis_fem_import is None or genesis_fem_import.ok else "failed",
            "notes": notes,
        }
    )
    return updated


def visual_mesh_path(bundle: Any) -> Path | None:
    transfer = bundle.texture_transfer
    if transfer is not None and transfer.ok and transfer.output_mesh_path is not None:
        return transfer.output_mesh_path
    texture = bundle.texture
    if texture is not None and texture.ok and texture.textured_mesh_path is not None:
        return texture.textured_mesh_path
    return None


def texture_path_from_bundle(bundle: Any) -> Path | None:
    transfer = bundle.texture_transfer
    if transfer is not None and transfer.ok and transfer.output_texture_path is not None:
        return transfer.output_texture_path
    texture = bundle.texture
    if texture is not None and texture.ok:
        return texture.texture_paths.get("base_color")
    return None


def _generated_mesh_notes(
    *,
    repair: Any | None,
    genesis_fem_import: Any | None,
    scale_metadata: dict[str, Any],
) -> list[str]:
    notes = [
        "Generated by the Planner-callable mesh asset action.",
        "Use runtime_path as the strict-manifold Genesis geometry for simulation/collision.",
        "visual_path is the seam-aware textured render artifact for the same logical asset, not a separate object to "
        "instantiate as an independent simulation body.",
        "Pass file_meshes_are_zup and scale exactly as listed; generated OBJ assets are provider Y-up unless stated "
        "otherwise.",
        "If texture transfer succeeded, visual_path binds the rebaked base color through its neighboring MTL file while "
        "runtime_path remains the repaired manifold geometry.",
        "Use texture_path as evidence metadata for the transferred base-color image and for texture preview checks.",
    ]
    if repair is None or not repair.ok:
        notes.append("Mesh repair did not produce a ready repaired mesh; runtime_path falls back to the downloaded mesh.")
    if genesis_fem_import is not None:
        notes.append(
            "Genesis FEM import validation passed for runtime_path with the listed scale and orientation."
            if genesis_fem_import.ok
            else f"Genesis FEM import validation failed: {genesis_fem_import.error}"
        )
    if scale_metadata["explicit_scale"] is not None:
        notes.append("Runtime scale is the Planner-requested uniform scale factor; per-axis stretching is avoided.")
    elif scale_metadata["desired_size"] is not None and scale_metadata["genesis_bbox"] is not None:
        notes.append(
            "Runtime scale is a scalar uniform fit factor estimated from the generated mesh bbox and requested bbox "
            "after Y-up to Genesis Z-up conversion; per-axis non-uniform stretching is intentionally avoided."
        )
    return notes


def failed_manifest_entry(request: dict[str, Any], error: str) -> dict[str, Any]:
    return {
        "logical_name": str(request.get("name", "mesh_asset")),
        "source_type": "generated_mesh",
        "runtime_path": "unavailable",
        "visual_path": None,
        "scale": _uniform_scale_factor(request.get("scale")),
        "bbox": request_size(request),
        "file_meshes_are_zup": False,
        "texture_path": None,
        "asset_request": _manifest_asset_request(request),
        "simulation_role": str(request.get("simulation_role", "scene prop")),
        "status": "failed",
        "notes": [error],
    }


def build_manifest(entries: list[dict[str, Any]], *, skipped_names: list[str]) -> dict[str, Any]:
    unresolved = [entry["logical_name"] for entry in entries if entry.get("status") != "ready"]
    unresolved.extend(f"Skipped asset request: {name}" for name in skipped_names)
    return {
        "assets": entries,
        "assumptions": [
            "Generated mesh runtime paths are written before code writers run, so workers should read this manifest.",
        ],
        "unresolved_risks": unresolved,
    }


def _scale_metadata_from_request(request: dict[str, Any], mesh_path: str | Path) -> dict[str, Any]:
    summary = load_mesh_asset_summary(mesh_path)
    mesh_bbox = vector3(summary.get("bbox_size"))
    genesis_bbox = _bbox_after_yup_to_zup(mesh_bbox)
    desired_size = request_size(request)
    explicit_scale = _uniform_scale_factor(request.get("scale"))
    scale = explicit_scale if explicit_scale is not None else (_scale_to_bbox(genesis_bbox, desired_size) or 1.0)
    return {
        "explicit_scale": explicit_scale,
        "desired_size": desired_size,
        "genesis_bbox": genesis_bbox,
        "runtime_bbox": None if genesis_bbox is None else [float(item) * float(scale) for item in genesis_bbox],
        "scale": scale,
    }


def _scale_to_bbox(mesh_bbox: list[float] | None, request_bbox: list[float] | None) -> float | None:
    if mesh_bbox is None or request_bbox is None:
        return None
    ratios: list[float] = []
    for mesh_size, requested_size in zip(mesh_bbox, request_bbox, strict=True):
        if mesh_size <= 0 or requested_size <= 0:
            return None
        ratios.append(float(requested_size) / float(mesh_size))
    if not ratios:
        return None
    return min(ratios)


def _uniform_scale_factor(value: object) -> float | None:
    if isinstance(value, (int, float)) and not isinstance(value, bool) and value > 0.0:
        return float(value)
    scale_vec = vector3(value)
    if scale_vec is None or any(item <= 0.0 for item in scale_vec):
        return None
    if max(scale_vec) - min(scale_vec) > 1e-12:
        return None
    return float(scale_vec[0])


def _manifest_asset_request(request: dict[str, Any]) -> dict[str, Any]:
    return {str(key): value for key, value in request.items()}


def _bbox_after_yup_to_zup(mesh_bbox: list[float] | None) -> list[float] | None:
    if mesh_bbox is None:
        return None
    return [float(mesh_bbox[0]), float(mesh_bbox[2]), float(mesh_bbox[1])]
