from __future__ import annotations

from pathlib import Path
from typing import Any


def manifest_entry_from_xml_validation(
    *,
    logical_name: str,
    xml_path: Path,
    validation_report: dict[str, Any],
    simulation_role: str = "articulated asset",
) -> dict[str, Any]:
    status = "ready" if validation_report.get("ok") else "failed"
    return {
        "logical_name": logical_name,
        "source_type": "mjcf",
        "runtime_path": str(xml_path.resolve()),
        "visual_path": None,
        "scale": None,
        "bbox": None,
        "file_meshes_are_zup": None,
        "texture_path": None,
        "joints": validation_report.get("joints", []),
        "actuators": validation_report.get("actuators", []),
        "control_interface": validation_report.get("control_interface", {}),
        "base": validation_report.get("base", {}),
        "validation": {
            "mujoco_ok": bool(validation_report.get("mujoco_ok")),
            "errors": validation_report.get("errors", []),
            "warnings": validation_report.get("warnings", []),
            "model_summary": validation_report.get("model_summary", {}),
        },
        "simulation_role": simulation_role,
        "status": status,
        "notes": [
            "Generated by the standalone Codex XML asset worker.",
            "Contains exactly one MJCF articulated body tree when validation is ready.",
            "Scene placement, lights, cameras, ground, projectiles, and task props must be added by scene/body writers.",
        ],
    }
