from __future__ import annotations


def runtime_helpers_source() -> list[str]:
    return [
        "def _to_serializable(value):",
        "    if hasattr(value, 'detach'):",
        "        value = value.detach()",
        "    if hasattr(value, 'cpu'):",
        "        value = value.cpu()",
        "    if hasattr(value, 'numpy'):",
        "        value = value.numpy()",
        "    if hasattr(value, 'tolist'):",
        "        return value.tolist()",
        "    return value",
        "",
        "",
        "def _count_contacts(contact_data):",
        "    valid_mask = contact_data.get('valid_mask')",
        "    if valid_mask is not None:",
        "        mask = _to_serializable(valid_mask)",
        "        if isinstance(mask, list):",
        "            stack = [mask]",
        "            count = 0",
        "            while stack:",
        "                current = stack.pop()",
        "                if isinstance(current, list):",
        "                    stack.extend(current)",
        "                else:",
        "                    count += int(bool(current))",
        "            return count",
        "        return int(bool(mask))",
        "",
        "    geom_a = _to_serializable(contact_data.get('geom_a', []))",
        "    if isinstance(geom_a, list):",
        "        if geom_a and isinstance(geom_a[0], list):",
        "            return len(geom_a[0])",
        "        return len(geom_a)",
        "    return 0",
        "",
        "",
        "def _iter_contact_geom_pairs(contact_data):",
        "    geom_a = _to_serializable(contact_data.get('geom_a', []))",
        "    geom_b = _to_serializable(contact_data.get('geom_b', []))",
        "    valid_mask = _to_serializable(contact_data.get('valid_mask')) if 'valid_mask' in contact_data else None",
        "    pairs = []",
        "",
        "    def _append_pairs(a_data, b_data, mask_data=None):",
        "        if isinstance(a_data, list) and isinstance(b_data, list) and a_data and isinstance(a_data[0], list):",
        "            for index in range(min(len(a_data), len(b_data))):",
        "                env_mask = None if mask_data is None else mask_data[index]",
        "                _append_pairs(a_data[index], b_data[index], env_mask)",
        "            return",
        "        if not isinstance(a_data, list) or not isinstance(b_data, list):",
        "            return",
        "        for index in range(min(len(a_data), len(b_data))):",
        "            if mask_data is not None and isinstance(mask_data, list) and index < len(mask_data) and not bool(mask_data[index]):",
        "                continue",
        "            a_item = a_data[index]",
        "            b_item = b_data[index]",
        "            if not isinstance(a_item, (int, float)) or isinstance(a_item, bool):",
        "                continue",
        "            if not isinstance(b_item, (int, float)) or isinstance(b_item, bool):",
        "                continue",
        "            pairs.append((int(a_item), int(b_item)))",
        "",
        "    _append_pairs(geom_a, geom_b, valid_mask)",
        "    return pairs",
        "",
        "",
        "def _contact_other_entities(contact_data, target_entity_name, scene_entities):",
        "    target_entity = scene_entities.get(target_entity_name)",
        "    if target_entity is None:",
        "        return []",
        "    try:",
        "        target_geom_start = int(target_entity.geom_start)",
        "        target_geom_end = int(target_entity.geom_end)",
        "    except Exception:",
        "        return []",
        "",
        "    def _entity_name_for_geom(geom_idx):",
        "        for entity_name, entity in scene_entities.items():",
        "            try:",
        "                geom_start = int(entity.geom_start)",
        "                geom_end = int(entity.geom_end)",
        "            except Exception:",
        "                continue",
        "            if geom_start <= geom_idx < geom_end:",
        "                return entity_name",
        "        return None",
        "",
        "    other_entities = []",
        "    seen = set()",
        "    for geom_a, geom_b in _iter_contact_geom_pairs(contact_data):",
        "        a_in_target = target_geom_start <= geom_a < target_geom_end",
        "        b_in_target = target_geom_start <= geom_b < target_geom_end",
        "        if a_in_target == b_in_target:",
        "            continue",
        "        other_geom = geom_b if a_in_target else geom_a",
        "        other_entity_name = _entity_name_for_geom(other_geom)",
        "        if other_entity_name is None or other_entity_name == target_entity_name or other_entity_name in seen:",
        "            continue",
        "        seen.add(other_entity_name)",
        "        other_entities.append(other_entity_name)",
        "    return other_entities",
        "",
        "",
        "def _is_floating_base_entity(entity):",
        "    try:",
        "        return int(entity.n_qs) >= 7 and int(entity.n_dofs) >= 6",
        "    except Exception:",
        "        return False",
        "",
        "",
        "def _as_float_vector(value):",
        "    data = _to_serializable(value)",
        "    if isinstance(data, list) and data and isinstance(data[0], list):",
        "        data = data[0]",
        "    if not isinstance(data, list):",
        "        return None",
        "    output = []",
        "    for component in data:",
        "        if not isinstance(component, (int, float)) or isinstance(component, bool):",
        "            return None",
        "        output.append(float(component))",
        "    return output",
        "",
        "",
        "def _get_floating_base_root_state(entity):",
        "    if not _is_floating_base_entity(entity):",
        "        return None",
        "    qpos = _as_float_vector(entity.get_qpos())",
        "    dofs_velocity = _as_float_vector(entity.get_dofs_velocity())",
        "    if qpos is None or dofs_velocity is None:",
        "        return None",
        "    if len(qpos) < 7 or len(dofs_velocity) < 6:",
        "        return None",
        "    return {",
        "        'pos': qpos[:3],",
        "        'quat': qpos[3:7],",
        "        'vel': dofs_velocity[:3],",
        "        'ang': dofs_velocity[3:6],",
        "    }",
        "",
        "",
        "def _get_entity_root_pos(entity, envs_idx=None):",
        "    if not _is_floating_base_entity(entity):",
        "        return entity.get_pos(envs_idx)",
        "    qpos = entity.get_qpos(envs_idx=envs_idx)",
        "    return qpos[..., :3]",
        "",
        "",
        "class _FollowRootPositionProxy:",
        "    def __init__(self, entity):",
        "        self._entity = entity",
        "",
        "    def get_pos(self, envs_idx=None):",
        "        return _get_entity_root_pos(self._entity, envs_idx=envs_idx)",
        "",
        "",
        "def _follow_entity_target(entity):",
        "    if _is_floating_base_entity(entity):",
        "        return _FollowRootPositionProxy(entity)",
        "    return entity",
        "",
        "",
        "def _resolve_dofs_idx_local(entity, *, dofs_idx_local, joint_names, values_length=None):",
        "    if dofs_idx_local is not None:",
        "        if values_length is not None and len(dofs_idx_local) != values_length:",
        "            raise ValueError(",
        "                f'Length mismatch: selected {len(dofs_idx_local)} dofs by `dofs_idx_local`, '",
        "                f'but received {values_length} values.'",
        "            )",
        "        return dofs_idx_local",
        "    if joint_names is None:",
        "        if values_length is None:",
        "            return None",
        "        expected = int(entity.n_dofs)",
        "        if values_length != expected:",
        "            raise ValueError(",
        "                'Length mismatch without DoF selector: '",
        "                f'entity has {expected} DoFs but received {values_length} values. '",
        "                'Provide `dofs_idx_local` or `joint_names`, or pass full-length values.'",
        "            )",
        "        return tuple(range(expected))",
        "",
        "    resolved = []",
        "    for joint_name in joint_names:",
        "        joint = entity.get_joint(name=joint_name)",
        "        joint_dofs = tuple(int(index) for index in joint.dofs_idx_local)",
        "        if len(joint_dofs) == 0:",
        "            raise ValueError(f'Joint `{joint_name}` has no DoFs.')",
        "        resolved.extend(joint_dofs)",
        "",
        "    if values_length is not None and len(resolved) != values_length:",
        "        raise ValueError(",
        "            'Length mismatch for joint selector: '",
        "            f'resolved {len(resolved)} dofs from `joint_names`, but received {values_length} values.'",
        "        )",
        "    return tuple(resolved)",
        "",
        "",
        "def _resolve_links_idx(entity, *, links_idx_local, link_names):",
        "    if links_idx_local is not None:",
        "        return tuple(int(entity.link_start + idx) for idx in links_idx_local)",
        "    if link_names is None:",
        "        return tuple(range(int(entity.link_start), int(entity.link_end)))",
        "",
        "    resolved = []",
        "    for link_name in link_names:",
        "        link = entity.get_link(name=link_name)",
        "        resolved.append(int(link.idx))",
        "    return tuple(resolved)",
        "",
        "",
        "def _to_scalar_or_tuple(value, *, expected_size, field_name):",
        "    if isinstance(value, tuple):",
        "        if len(value) != expected_size:",
        "            raise ValueError(",
        "                f'Length mismatch: `{field_name}` expects {expected_size} values, but got {len(value)}.'",
        "            )",
        "        return tuple(float(component) for component in value)",
        "    return float(value)",
    ]
