from __future__ import annotations


def runtime_helpers_source() -> list[str]:
    return [
        "def _to_serializable(value):",
        "    if hasattr(value, 'detach'):",
        "        value = value.detach()",
        "    if hasattr(value, 'cpu'):",
        "        value = value.cpu()",
        "    if hasattr(value, 'numpy'):",
        "        value = value.numpy()",
        "    if hasattr(value, 'tolist'):",
        "        return value.tolist()",
        "    return value",
        "",
        "",
        "def _count_contacts(contact_data):",
        "    valid_mask = contact_data.get('valid_mask')",
        "    if valid_mask is not None:",
        "        mask = _to_serializable(valid_mask)",
        "        if isinstance(mask, list):",
        "            stack = [mask]",
        "            count = 0",
        "            while stack:",
        "                current = stack.pop()",
        "                if isinstance(current, list):",
        "                    stack.extend(current)",
        "                else:",
        "                    count += int(bool(current))",
        "            return count",
        "        return int(bool(mask))",
        "",
        "    geom_a = _to_serializable(contact_data.get('geom_a', []))",
        "    if isinstance(geom_a, list):",
        "        if geom_a and isinstance(geom_a[0], list):",
        "            return len(geom_a[0])",
        "        return len(geom_a)",
        "    return 0",
        "",
        "",
        "def _iter_contact_geom_pairs(contact_data):",
        "    geom_a = _to_serializable(contact_data.get('geom_a', []))",
        "    geom_b = _to_serializable(contact_data.get('geom_b', []))",
        "    valid_mask = _to_serializable(contact_data.get('valid_mask')) if 'valid_mask' in contact_data else None",
        "    pairs = []",
        "",
        "    def _append_pairs(a_data, b_data, mask_data=None):",
        "        if isinstance(a_data, list) and isinstance(b_data, list) and a_data and isinstance(a_data[0], list):",
        "            for index in range(min(len(a_data), len(b_data))):",
        "                env_mask = None if mask_data is None else mask_data[index]",
        "                _append_pairs(a_data[index], b_data[index], env_mask)",
        "            return",
        "        if not isinstance(a_data, list) or not isinstance(b_data, list):",
        "            return",
        "        for index in range(min(len(a_data), len(b_data))):",
        "            if mask_data is not None and isinstance(mask_data, list) and index < len(mask_data) and not bool(mask_data[index]):",
        "                continue",
        "            a_item = a_data[index]",
        "            b_item = b_data[index]",
        "            if not isinstance(a_item, (int, float)) or isinstance(a_item, bool):",
        "                continue",
        "            if not isinstance(b_item, (int, float)) or isinstance(b_item, bool):",
        "                continue",
        "            pairs.append((int(a_item), int(b_item)))",
        "",
        "    _append_pairs(geom_a, geom_b, valid_mask)",
        "    return pairs",
        "",
        "",
        "def _contact_other_entities(contact_data, target_entity_name, scene_entities):",
        "    target_entity = scene_entities.get(target_entity_name)",
        "    if target_entity is None:",
        "        return []",
        "    try:",
        "        target_geom_start = int(target_entity.geom_start)",
        "        target_geom_end = int(target_entity.geom_end)",
        "    except Exception:",
        "        return []",
        "",
        "    def _entity_name_for_geom(geom_idx):",
        "        for entity_name, entity in scene_entities.items():",
        "            try:",
        "                geom_start = int(entity.geom_start)",
        "                geom_end = int(entity.geom_end)",
        "            except Exception:",
        "                continue",
        "            if geom_start <= geom_idx < geom_end:",
        "                return entity_name",
        "        return None",
        "",
        "    other_entities = []",
        "    seen = set()",
        "    for geom_a, geom_b in _iter_contact_geom_pairs(contact_data):",
        "        a_in_target = target_geom_start <= geom_a < target_geom_end",
        "        b_in_target = target_geom_start <= geom_b < target_geom_end",
        "        if a_in_target == b_in_target:",
        "            continue",
        "        other_geom = geom_b if a_in_target else geom_a",
        "        other_entity_name = _entity_name_for_geom(other_geom)",
        "        if other_entity_name is None or other_entity_name == target_entity_name or other_entity_name in seen:",
        "            continue",
        "        seen.add(other_entity_name)",
        "        other_entities.append(other_entity_name)",
        "    return other_entities",
        "",
        "",
        "def _first_aabb(aabb_value):",
        "    data = _to_serializable(aabb_value)",
        "    if not isinstance(data, list):",
        "        return None",
        "    if len(data) == 2 and all(isinstance(item, list) for item in data):",
        "        mins = _as_float_vector(data[0])",
        "        maxs = _as_float_vector(data[1])",
        "        if mins is None or maxs is None or len(mins) != 3 or len(maxs) != 3:",
        "            return None",
        "        return mins, maxs",
        "    if len(data) >= 1 and isinstance(data[0], list):",
        "        first = data[0]",
        "        if isinstance(first, list) and len(first) == 2 and all(isinstance(item, list) for item in first):",
        "            mins = _as_float_vector(first[0])",
        "            maxs = _as_float_vector(first[1])",
        "            if mins is None or maxs is None or len(mins) != 3 or len(maxs) != 3:",
        "                return None",
        "            return mins, maxs",
        "    return None",
        "",
        "",
        "def _entity_bbox(entity, deformable_observation_state=None):",
        "    if deformable_observation_state is not None:",
        "        bbox_min = _as_float_vector(deformable_observation_state.get('bbox_min'))",
        "        bbox_max = _as_float_vector(deformable_observation_state.get('bbox_max'))",
        "        if bbox_min is not None and bbox_max is not None and len(bbox_min) == 3 and len(bbox_max) == 3:",
        "            return bbox_min, bbox_max",
        "    if _is_deformable_entity(entity):",
        "        deformable_state = _get_deformable_observation_state(entity)",
        "        if deformable_state is None:",
        "            return None",
        "        bbox_min = _as_float_vector(deformable_state.get('bbox_min'))",
        "        bbox_max = _as_float_vector(deformable_state.get('bbox_max'))",
        "        if bbox_min is None or bbox_max is None or len(bbox_min) != 3 or len(bbox_max) != 3:",
        "            return None",
        "        return bbox_min, bbox_max",
        "    get_aabb = getattr(entity, 'get_AABB', None)",
        "    if get_aabb is None:",
        "        return None",
        "    try:",
        "        return _first_aabb(get_aabb(allow_fast_approx=True))",
        "    except TypeError:",
        "        try:",
        "            return _first_aabb(get_aabb())",
        "        except Exception:",
        "            return None",
        "    except Exception:",
        "        return None",
        "",
        "",
        "def _aabb_overlaps(lhs_min, lhs_max, rhs_min, rhs_max, eps=1e-6):",
        "    return all(lhs_min[i] <= rhs_max[i] + eps and rhs_min[i] <= lhs_max[i] + eps for i in range(3))",
        "",
        "",
        "def _bbox_contact_other_entities(target_entity_name, target_bbox, scene_entities):",
        "    if target_bbox is None:",
        "        return []",
        "    target_min, target_max = target_bbox",
        "    overlaps = []",
        "    for other_entity_name, other_entity in scene_entities.items():",
        "        if other_entity_name == target_entity_name:",
        "            continue",
        "        other_bbox = _entity_bbox(other_entity)",
        "        if other_bbox is None:",
        "            continue",
        "        other_min, other_max = other_bbox",
        "        if _aabb_overlaps(target_min, target_max, other_min, other_max):",
        "            overlaps.append(other_entity_name)",
        "    return overlaps",
        "",
        "",
        "def _observed_contact_summary(target_entity_name, target_entity, scene_entities, deformable_observation_state=None, include_count=False):",
        "    target_bbox = _entity_bbox(target_entity, deformable_observation_state=deformable_observation_state)",
        "    other_entities = _bbox_contact_other_entities(target_entity_name, target_bbox, scene_entities)",
        "    return {",
        "        'other_entities': other_entities,",
        "        'exact': False,",
        "        'source': 'aabb_overlap',",
        "        **({'count': len(other_entities)} if include_count else {}),",
        "    }",
        "",
        "",
        "def _is_floating_base_entity(entity):",
        "    try:",
        "        return int(entity.n_qs) >= 7 and int(entity.n_dofs) >= 6",
        "    except Exception:",
        "        return False",
        "",
        "",
        "def _is_deformable_entity(entity):",
        "    return getattr(entity.__class__, '__name__', '') in {'PBD2DEntity', 'PBD3DEntity', 'PBDParticleEntity', 'PBDFreeParticleEntity', 'FEMEntity'}",
        "",
        "",
        "def _as_float_vector(value):",
        "    data = _to_serializable(value)",
        "    if isinstance(data, list) and data and isinstance(data[0], list):",
        "        data = data[0]",
        "    if not isinstance(data, list):",
        "        return None",
        "    output = []",
        "    for component in data:",
        "        if not isinstance(component, (int, float)) or isinstance(component, bool):",
        "            return None",
        "        output.append(float(component))",
        "    return output",
        "",
        "",
        "def _get_floating_base_root_state(entity):",
        "    if not _is_floating_base_entity(entity):",
        "        return None",
        "    qpos = _as_float_vector(entity.get_qpos())",
        "    dofs_velocity = _as_float_vector(entity.get_dofs_velocity())",
        "    if qpos is None or dofs_velocity is None:",
        "        return None",
        "    if len(qpos) < 7 or len(dofs_velocity) < 6:",
        "        return None",
        "    return {",
        "        'pos': qpos[:3],",
        "        'quat': qpos[3:7],",
        "        'vel': dofs_velocity[:3],",
        "        'ang': dofs_velocity[3:6],",
        "    }",
        "",
        "",
        "def _as_vec3_rows(value):",
        "    data = _to_serializable(value)",
        "    if isinstance(data, list) and data and isinstance(data[0], list) and data[0] and isinstance(data[0][0], list):",
        "        data = data[0]",
        "    if not isinstance(data, list):",
        "        return None",
        "    rows = []",
        "    for row in data:",
        "        if not isinstance(row, list) or len(row) != 3:",
        "            return None",
        "        converted = []",
        "        for component in row:",
        "            if not isinstance(component, (int, float)) or isinstance(component, bool):",
        "                return None",
        "            converted.append(float(component))",
        "        rows.append(converted)",
        "    return rows",
        "",
        "",
        "def _mean_vec3(rows):",
        "    if not rows:",
        "        return [0.0, 0.0, 0.0]",
        "    count = float(len(rows))",
        "    return [",
        "        sum(row[0] for row in rows) / count,",
        "        sum(row[1] for row in rows) / count,",
        "        sum(row[2] for row in rows) / count,",
        "    ]",
        "",
        "",
        "def _bbox_from_rows(rows):",
        "    mins = [min(row[i] for row in rows) for i in range(3)]",
        "    maxs = [max(row[i] for row in rows) for i in range(3)]",
        "    return mins, maxs, [maxs[i] - mins[i] for i in range(3)]",
        "",
        "",
        "def _displacement_stats(current_rows, initial_rows):",
        "    if initial_rows is None or len(current_rows) != len(initial_rows):",
        "        return None, None",
        "    magnitudes = []",
        "    for current, initial in zip(current_rows, initial_rows):",
        "        dx = current[0] - initial[0]",
        "        dy = current[1] - initial[1]",
        "        dz = current[2] - initial[2]",
        "        magnitudes.append((dx * dx + dy * dy + dz * dz) ** 0.5)",
        "    if not magnitudes:",
        "        return 0.0, 0.0",
        "    return sum(magnitudes) / len(magnitudes), max(magnitudes)",
        "",
        "",
        "def _get_deformable_observation_state(entity):",
        "    if not _is_deformable_entity(entity):",
        "        return None",
        "    try:",
        "        if getattr(entity.__class__, '__name__', '') == 'FEMEntity':",
        "            fem_state = entity.get_state()",
        "            pos_tensor = fem_state.pos",
        "            vel_tensor = fem_state.vel",
        "            initial_source = getattr(entity, 'init_positions', None)",
        "        else:",
        "            pos_tensor = entity.get_particles_pos()",
        "            vel_tensor = entity.get_particles_vel()",
        "            initial_source = getattr(entity, '_particles', None)",
        "    except Exception:",
        "        return None",
        "    pos_rows = _as_vec3_rows(_to_serializable(pos_tensor))",
        "    vel_rows = _as_vec3_rows(_to_serializable(vel_tensor))",
        "    if pos_rows is None or vel_rows is None:",
        "        return None",
        "    bbox_min, bbox_max, bbox_size = _bbox_from_rows(pos_rows)",
        "    initial_rows = _as_vec3_rows(_to_serializable(initial_source))",
        "    disp_mean, disp_max = _displacement_stats(pos_rows, initial_rows)",
        "    return {",
        "        'pos': _mean_vec3(pos_rows),",
        "        'vel': _mean_vec3(vel_rows),",
        "        'bbox_min': bbox_min,",
        "        'bbox_max': bbox_max,",
        "        'bbox_size': bbox_size,",
        "        'vertex_disp_mean': disp_mean,",
        "        'vertex_disp_max': disp_max,",
        "    }",
        "",
        "",
        "def _get_entity_root_pos(entity, envs_idx=None):",
        "    if not _is_floating_base_entity(entity):",
        "        return entity.get_pos(envs_idx)",
        "    qpos = entity.get_qpos(envs_idx=envs_idx)",
        "    return qpos[..., :3]",
        "",
        "",
        "def _get_deformable_entity_com_pos(entity):",
        "    deformable_state = _get_deformable_observation_state(entity)",
        "    if deformable_state is None:",
        "        return None",
        "    pos = deformable_state.get('pos')",
        "    if isinstance(pos, list) and len(pos) == 3:",
        "        return pos",
        "    return None",
        "",
        "",
        "class _FollowRootPositionProxy:",
        "    def __init__(self, entity):",
        "        self._entity = entity",
        "",
        "    def get_pos(self, envs_idx=None):",
        "        return _get_entity_root_pos(self._entity, envs_idx=envs_idx)",
        "",
        "",
        "class _FollowDeformablePositionProxy:",
        "    def __init__(self, entity):",
        "        self._entity = entity",
        "",
        "    def get_pos(self, envs_idx=None):",
        "        pos = _get_deformable_entity_com_pos(self._entity)",
        "        if pos is None:",
        "            raise ValueError('Deformable follow target does not have a valid COM position.')",
        "        pos_tensor = gs.torch.as_tensor(pos, dtype=gs.tc_float, device=gs.device)",
        "        if envs_idx is None or envs_idx == ():",
        "            return pos_tensor",
        "        try:",
        "            n_envs = len(envs_idx)",
        "        except TypeError:",
        "            return pos_tensor",
        "        return pos_tensor.reshape((1, 3)).expand((n_envs, 3))",
        "",
        "",
        "def _follow_entity_target(entity):",
        "    if _is_floating_base_entity(entity):",
        "        return _FollowRootPositionProxy(entity)",
        "    if _is_deformable_entity(entity):",
        "        return _FollowDeformablePositionProxy(entity)",
        "    return entity",
        "",
        "",
        "def _resolve_dofs_idx_local(entity, *, dofs_idx_local, joint_names, values_length=None):",
        "    if dofs_idx_local is not None:",
        "        if values_length is not None and len(dofs_idx_local) != values_length:",
        "            raise ValueError(",
        "                f'Length mismatch: selected {len(dofs_idx_local)} dofs by `dofs_idx_local`, '",
        "                f'but received {values_length} values.'",
        "            )",
        "        return dofs_idx_local",
        "    if joint_names is None:",
        "        if values_length is None:",
        "            return None",
        "        expected = int(entity.n_dofs)",
        "        if values_length != expected:",
        "            raise ValueError(",
        "                'Length mismatch without DoF selector: '",
        "                f'entity has {expected} DoFs but received {values_length} values. '",
        "                'Provide `dofs_idx_local` or `joint_names`, or pass full-length values.'",
        "            )",
        "        return tuple(range(expected))",
        "",
        "    resolved = []",
        "    for joint_name in joint_names:",
        "        joint = entity.get_joint(name=joint_name)",
        "        joint_dofs = tuple(int(index) for index in joint.dofs_idx_local)",
        "        if len(joint_dofs) == 0:",
        "            raise ValueError(f'Joint `{joint_name}` has no DoFs.')",
        "        resolved.extend(joint_dofs)",
        "",
        "    if values_length is not None and len(resolved) != values_length:",
        "        raise ValueError(",
        "            'Length mismatch for joint selector: '",
        "            f'resolved {len(resolved)} dofs from `joint_names`, but received {values_length} values.'",
        "        )",
        "    return tuple(resolved)",
        "",
        "",
        "def _resolve_links_idx(entity, *, links_idx_local, link_names):",
        "    if links_idx_local is not None:",
        "        return tuple(int(entity.link_start + idx) for idx in links_idx_local)",
        "    if link_names is None:",
        "        return tuple(range(int(entity.link_start), int(entity.link_end)))",
        "",
        "    resolved = []",
        "    for link_name in link_names:",
        "        link = entity.get_link(name=link_name)",
        "        resolved.append(int(link.idx))",
        "    return tuple(resolved)",
        "",
        "",
        "def _to_scalar_or_tuple(value, *, expected_size, field_name):",
        "    if isinstance(value, tuple):",
        "        if len(value) != expected_size:",
        "            raise ValueError(",
        "                f'Length mismatch: `{field_name}` expects {expected_size} values, but got {len(value)}.'",
        "            )",
        "        return tuple(float(component) for component in value)",
        "    return float(value)",
    ]
